import { getCookie } from 'cookies-next'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Router from 'next/router'
import { useEffect, useState, useCallback } from 'react'
import Loader from '../components/Loader'
import Navbar from '../components/Navbar'
import SelectDropdown from '../components/SelectDropdown'
import Timeline from '../components/Timeline'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [list, setList] = useState(
    [
      {
        id: 0,
        value: 'Hello World0'
      },
      {
        id: 1,
        value: 'Hello World1'
      }
    ]
  )
  const [isLoading, setIsloading] = useState(true);
  const [count, setCount] = useState(0);
  const[dropdownList, setDropdownList] = useState({
    header: "Gender",
    onSelected: onSelected,
    list: [
      {
        name : "Male",
        id : "0",
        
      },
      {
        name : "Female",
        id : "1",
      },
    ]
  });
  function onSelected(selected: number){
    console.log(selected);
  }
  useEffect(()=> {
    console.log('Home Component')
    console.log(getCookie("myToken"))
    const timeout = setTimeout(()=> {
      setIsloading(false);
    },1000)
  })
  return (
    <div >
      <Head>
        <title>Web App Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loader isLoading = {isLoading} />
      <Navbar />
      <main className='container'>
        <section className=''>
          <div className="main">
            <div className='row' >
              <div className='col-5 p-2' style={{display: 'flex', flexDirection: 'column',justifyContent: 'center', overflow: 'hidden'}}>
                <div className=''>
                  <div className='environment'></div>
                  <h1 className='title glitch layers' data-text='INSTEADIZE'><span>INSTEADIZE</span></h1>
                </div>
                <div className='mt-9'>
                  <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur incidunt officiis distinctio magnam, assumenda rem ipsum earum cumque quasi veritatis similique enim, consequuntur eum voluptate ab voluptas! Id, sequi sed!</p>
                </div>
                <span className='m-auto mt-4 w-100' style={{maxWidth: '520px', border: '1px solid #fff'}}><a style={{padding: '8px'}} className='text-ellipsis'>contract | 0xf70F246D961246c9B48dc0D8Cd621986B6919E2C</a></span>
                {/* <table className='mt-4 w-100'>
                  <tbody>
                    <tr>
                      <td style={{color: 'white', width: '80px'}}>contract</td>
                      <td className='w-100'>
                        <span className='text-ellipsis'>
                          0xf70F246D961246c9B48dc0D8Cd621986B6919E2C
                        </span>
                      </td>
                    </tr>
                  </tbody>
                </table> */}
                <div className='mt-9'>
                  <h1 style={{color: 'white'}}>Download now for free</h1>
                  <div className='d-flex mt-2 '>
                    <button className='btn-primary d-flex'><a className='fa fa-2x fa-apple'></a><a style={{lineHeight: '28px'}}>ios</a></button>
                    <button className='btn-primary d-flex'><a className='fa fa-2x fa-android'></a><a style={{lineHeight: '28px'}}>Android</a></button>
                    <button className='btn-primary d-flex'><a className='fa fa-2x fa-warning'></a><a style={{lineHeight: '28px'}}>Android</a></button>
                  </div>
                </div>
                
              </div>
              <div className='col-5 hero' style={{backgroundColor: "deepskyblue", position: 'relative', padding:'10px'}}>
                <Image src='/vercel.svg' layout='fill'/>
              </div>
            </div>
            
            <p className={styles.description}>
              Get started by editing{' '}
              <code className={styles.code}>pages/index.tsx</code>
              <br/>
              {getCookie("myToken")}
            </p>
          </div>
        </section>
        <section >
          <video controls src='/video0.mp4'/>
        </section>
        <section className=''>
          <Timeline/>
        </section>
        <section>
          <div className='main'>
            <SelectDropdown {...dropdownList}/>
          </div>
        </section>
      </main>
     

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
