import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Router from 'next/router'
import { useEffect, useState, useCallback } from 'react'
import Loader from '../components/Loader'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [isLoading, setIsloading] = useState(true);
  const [count, setCount] = useState(0);
  useEffect(()=> {
    console.log('Home Component')
    const timeout = setTimeout(()=> {
      setIsloading(false);
    },2500)
  })

  const Counter = () => {
    Router.push('/api/hello')
    setCount((prev) => prev+1);
    document.getElementsByTagName('h2')[0].innerHTML = `Count ${count}`;
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loader isLoading = {isLoading} />
      <Navbar />
      <main className='container'>
        <section className='' style={{backgroundColor: "red"}}>
          <div className="main">
            <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>
            <p className={styles.description}>
              Get started by editing{' '}
              <code className={styles.code}>pages/index.tsx</code>
            </p>

            <div className={styles.grid}>
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>

              <a href="https://nextjs.org/learn" className={styles.card}>
                <h2>Learn &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </a>

              <iframe width="853" height="480" src="https://www.youtube.com/embed/OBqw818mQ1E" title="SiM – The Rumbling (OFFICIAL VIDEO)"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
              
              <div className="card">
                <div className='card-content'>
                  <Image src="/vercel.svg" width="320px" height="320px"></Image>
                </div>
                <div className='card-info'>
                  <h4>Name: sdsdsd</h4>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, cumque fugit modi minus dolor, numquam fuga, sequi recusandae eaque deleniti non maiores aspernatur quisquam eos perferendis quam autem similique quod!</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className='' style={{backgroundColor: ""}}>
          <div className="main">
            <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>
            <p className={styles.description}>
              Get started by editing{' '}
              <code className={styles.code}>pages/index.tsx</code>
            </p>

            <div className={styles.grid}>
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>

              <a href="https://nextjs.org/learn" className={styles.card}>
                <h2>Learn &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </a>

              <div className="card">
                <div className='card-content'>
                  <video width="320" height="240" controls src='/WIN_20211107_05_15_48_Pro.mp4'/>

                </div>
                <div className='card-info'>
                  <h4>Name: sdsdsd</h4>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, cumque fugit modi minus dolor, numquam fuga, sequi recusandae eaque deleniti non maiores aspernatur quisquam eos perferendis quam autem similique quod!</p>
                </div>
              </div>

              <div className="card">
                <div className='card-content'>
                  <Image src="/vercel.svg" width="320px" height="320px"></Image>
                </div>
                <div className='card-info'>
                  <h4>Name: sdsdsd</h4>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, cumque fugit modi minus dolor, numquam fuga, sequi recusandae eaque deleniti non maiores aspernatur quisquam eos perferendis quam autem similique quod!</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
     

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
